apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{.Values.storageClassName}}
  resources:
    requests:
      storage: 19Gi