apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-persistent-storage-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storageLimit }}