apiVersion: v1
kind: Service
metadata:
  name: "kibana-svc"
  namespace: {{ .Values.namespace }}
  labels:
    app: "kibana-svc"
spec:
  type: {{ .Values.kibanaService.type }}
  ports:
    - port: {{ .Values.kibanaService.port }}
      targetPort: 5601
      protocol: TCP
      name: http
  selector:
    app: "kibana"
