apiVersion: v1
kind: Service
metadata:
  name: "elasticsearch-svc"
  namespace: {{ .Values.namespace }}
  labels:
    app: "elasticsearch-svc"
spec:
  type: {{ .Values.esService.type }}
  ports:
    - port: {{ .Values.esService.port }}
      targetPort: 9200
      protocol: TCP
      name: http
  selector:
    app: "elasticsearch"
